// ============================================================
//  PAROLE.JS — Database parole per il gioco Impostore
//  Aggiungi quante coppie vuoi seguendo il formato:
//  { normal: "Parola normale", wild: "Parola di Mister Wild" }
// ============================================================

const WORD_PAIRS = [

  // --- App & Social ---
  { normal: "Instagram", wild: "Facebook" },
  { normal: "WhatsApp", wild: "Telegram" },
  { normal: "Netflix", wild: "Disney+" },
  { normal: "YouTube", wild: "TikTok" },
  { normal: "Spotify", wild: "Apple Music" },
  { normal: "iPhone", wild: "Samsung Galaxy" },
  { normal: "PlayStation", wild: "Xbox" },
  { normal: "Amazon", wild: "eBay" },
  { normal: "Google Maps", wild: "Waze" },
  { normal: "McDonald's", wild: "Burger King" },

  // --- Film & Cartoni ---
  { normal: "Harry Potter", wild: "Il Signore degli Anelli" },
  { normal: "Il Re Leone", wild: "Dumbo" },
  { normal: "Shrek", wild: "Kung Fu Panda" },
  { normal: "Toy Story", wild: "Cars" },
  { normal: "Frozen", wild: "Rapunzel" },
  { normal: "Cenerentola", wild: "Biancaneve" },
  { normal: "Pinocchio", wild: "Pollicino" },
  { normal: "Aladdin", wild: "La Bella e la Bestia" },
  { normal: "Titanic", wild: "Il Gladiatore" },
  { normal: "Spider-Man", wild: "Batman" },
  { normal: "Jurassic Park", wild: "King Kong" },
  { normal: "La Casa di Carta", wild: "Squid Game" },
  { normal: "Naruto", wild: "Dragon Ball" },
  { normal: "Forrest Gump", wild: "Cast Away" },
  { normal: "Indiana Jones", wild: "James Bond" },
  { normal: "Cappuccetto Rosso", wild: "Hansel e Gretel" },
  { normal: "Superman", wild: "Batman" },
  { normal: "Topolino", wild: "Paperino" },
  { normal: "Asterix", wild: "Obelix" },
  { normal: "Dracula", wild: "Frankenstein" },

  // --- Cibo ---
  { normal: "Pizza", wild: "Focaccia" },
  { normal: "Hamburger", wild: "Hot dog" },
  { normal: "Gelato", wild: "Sorbetto" },
  { normal: "Pasta al pomodoro", wild: "Pasta in bianco" },
  { normal: "Lasagne", wild: "Pasta al forno" },
  { normal: "Patatine fritte", wild: "Patatine al forno" },
  { normal: "Carbonara", wild: "Amatriciana" },
  { normal: "Ravioli", wild: "Tortellini" },
  { normal: "Risotto", wild: "Minestra" },
  { normal: "Polpette", wild: "Cotoletta" },
  { normal: "Bistecca", wild: "Pollo arrosto" },
  { normal: "Prosciutto cotto", wild: "Prosciutto crudo" },
  { normal: "Mozzarella", wild: "Ricotta" },
  { normal: "Salame", wild: "Mortadella" },
  { normal: "Panino", wild: "Tramezzino" },
  { normal: "Pane", wild: "Grissino" },
  { normal: "Uovo fritto", wild: "Uovo sodo" },
  { normal: "Frittata", wild: "Omelette" },
  { normal: "Insalata", wild: "Verdure grigliate" },
  { normal: "Gamberetti", wild: "Calamari" },
  { normal: "Cozze", wild: "Vongole" },
  { normal: "Sushi", wild: "Kebab" },
  { normal: "Pesto", wild: "Ragù" },
  { normal: "Maionese", wild: "Ketchup" },

  // --- Dolci & Colazione ---
  { normal: "Tiramisù", wild: "Panna cotta" },
  { normal: "Cornetto", wild: "Brioche" },
  { normal: "Nutella", wild: "Marmellata" },
  { normal: "Biscotti", wild: "Wafer" },
  { normal: "Torta di compleanno", wild: "Crostata" },
  { normal: "Cioccolato fondente", wild: "Cioccolato al latte" },
  { normal: "Caramella", wild: "Gomma da masticare" },
  { normal: "Panettone", wild: "Pandoro" },
  { normal: "Gelato al cioccolato", wild: "Gelato alla fragola" },
  { normal: "Granita", wild: "Frappè" },
  { normal: "Kinder Bueno", wild: "Kinder Cereali" },
  { normal: "Oreo", wild: "Ringo" },

  // --- Bevande ---
  { normal: "Coca-Cola", wild: "Pepsi" },
  { normal: "Fanta", wild: "Sprite" },
  { normal: "Cappuccino", wild: "Macchiato" },
  { normal: "Caffè espresso", wild: "Caffè americano" },
  { normal: "Cioccolata calda", wild: "Latte caldo" },
  { normal: "Succo d'arancia", wild: "Succo di mela" },
  { normal: "Tè caldo", wild: "Tè freddo" },
  { normal: "Acqua frizzante", wild: "Acqua naturale" },
  { normal: "Birra", wild: "Vino" },
  { normal: "Vino rosso", wild: "Vino bianco" },
  { normal: "Prosecco", wild: "Champagne" },
  { normal: "Yogurt", wild: "Latte" },

  // --- Frutta ---
  { normal: "Mela", wild: "Pera" },
  { normal: "Arancia", wild: "Mandarino" },
  { normal: "Fragola", wild: "Lampone" },
  { normal: "Uva", wild: "Mirtillo" },
  { normal: "Limone", wild: "Lime" },
  { normal: "Anguria", wild: "Melone" },
  { normal: "Pesca", wild: "Albicocca" },
  { normal: "Ciliegia", wild: "Susina" },
  { normal: "Kiwi", wild: "Mango" },
  { normal: "Ananas", wild: "Papaya" },
  { normal: "Banana", wild: "Mango" },
  { normal: "Noce", wild: "Nocciola" },
  { normal: "Mandorla", wild: "Pistacchio" },
  { normal: "Castagna", wild: "Noce" },

  // --- Verdura ---
  { normal: "Pomodoro", wild: "Peperone" },
  { normal: "Zucchina", wild: "Melanzana" },
  { normal: "Carota", wild: "Patata" },
  { normal: "Insalata", wild: "Spinaci" },
  { normal: "Cipolla", wild: "Aglio" },
  { normal: "Fagioli", wild: "Piselli" },
  { normal: "Funghi", wild: "Carciofi" },
  { normal: "Mais", wild: "Grano" },

  // --- Animali comuni ---
  { normal: "Cane", wild: "Gatto" },
  { normal: "Leone", wild: "Tigre" },
  { normal: "Elefante", wild: "Rinoceronte" },
  { normal: "Delfino", wild: "Balena" },
  { normal: "Aquila", wild: "Falco" },
  { normal: "Coniglio", wild: "Criceto" },
  { normal: "Squalo", wild: "Polpo" },
  { normal: "Coccodrillo", wild: "Alligatore" },
  { normal: "Serpente", wild: "Lucertola" },
  { normal: "Tartaruga", wild: "Lumaca" },
  { normal: "Cavallo", wild: "Asino" },
  { normal: "Mucca", wild: "Pecora" },
  { normal: "Maiale", wild: "Cinghiale" },
  { normal: "Gallina", wild: "Tacchino" },
  { normal: "Oca", wild: "Anatra" },
  { normal: "Pinguino", wild: "Foca" },
  { normal: "Orso", wild: "Lupo" },
  { normal: "Volpe", wild: "Lepre" },
  { normal: "Gorilla", wild: "Scimpanzé" },
  { normal: "Giraffa", wild: "Zebra" },
  { normal: "Cammello", wild: "Lama" },
  { normal: "Pappagallo", wild: "Canarino" },
  { normal: "Piccione", wild: "Rondine" },
  { normal: "Ape", wild: "Farfalla" },
  { normal: "Ragno", wild: "Formica" },
  { normal: "Rana", wild: "Rospo" },
  { normal: "Topo", wild: "Ratto" },

  // --- Sport ---
  { normal: "Calcio", wild: "Rugby" },
  { normal: "Tennis", wild: "Padel" },
  { normal: "Nuoto", wild: "Pallanuoto" },
  { normal: "Basket", wild: "Pallavolo" },
  { normal: "Sci", wild: "Snowboard" },
  { normal: "Boxe", wild: "Karate" },
  { normal: "Formula 1", wild: "MotoGP" },
  { normal: "Ciclismo", wild: "Corsa a piedi" },
  { normal: "Golf", wild: "Minigolf" },
  { normal: "Ping pong", wild: "Badminton" },
  { normal: "Judo", wild: "Lotta" },
  { normal: "Surf", wild: "Sci d'acqua" },
  { normal: "Pattinaggio", wild: "Skateboard" },
  { normal: "Tiro con l'arco", wild: "Lancio del giavellotto" },
  { normal: "Ginnastica", wild: "Danza sportiva" },
  { normal: "Baseball", wild: "Cricket" },
  { normal: "Hockey", wild: "Curling" },
  { normal: "Maratona", wild: "Triathlon" },

  // --- Luoghi ---
  { normal: "Spiaggia", wild: "Piscina" },
  { normal: "Montagna", wild: "Collina" },
  { normal: "Parco", wild: "Giardino" },
  { normal: "Supermercato", wild: "Mercato" },
  { normal: "Ospedale", wild: "Farmacia" },
  { normal: "Chiesa", wild: "Municipio" },
  { normal: "Castello", wild: "Torre" },
  { normal: "Zoo", wild: "Acquario" },
  { normal: "Cinema", wild: "Teatro" },
  { normal: "Ristorante", wild: "Pizzeria" },
  { normal: "Bar", wild: "Gelateria" },
  { normal: "Palestra", wild: "Piscina" },
  { normal: "Discoteca", wild: "Pub" },
  { normal: "Stadio", wild: "Palazzetto" },
  { normal: "Biblioteca", wild: "Libreria" },
  { normal: "Aeroporto", wild: "Stazione dei treni" },
  { normal: "Scuola", wild: "Università" },
  { normal: "Parrucchiere", wild: "Barbiere" },
  { normal: "Banca", wild: "Ufficio postale" },
  { normal: "Pizzeria", wild: "Braceria" },
  { normal: "Roma", wild: "Milano" },
  { normal: "Napoli", wild: "Palermo" },
  { normal: "Firenze", wild: "Venezia" },
  { normal: "Londra", wild: "Parigi" },
  { normal: "New York", wild: "Los Angeles" },
  { normal: "Mare", wild: "Lago" },
  { normal: "Foresta", wild: "Giungla" },
  { normal: "Deserto", wild: "Savana" },
  { normal: "Isola", wild: "Penisola" },

  // --- Trasporti ---
  { normal: "Aereo", wild: "Elicottero" },
  { normal: "Treno", wild: "Tram" },
  { normal: "Bicicletta", wild: "Monopattino" },
  { normal: "Taxi", wild: "Bus" },
  { normal: "Nave", wild: "Traghetto" },
  { normal: "Ambulanza", wild: "Polizia" },
  { normal: "Camion", wild: "Furgone" },
  { normal: "Moto", wild: "Vespa" },
  { normal: "Macchina", wild: "SUV" },
  { normal: "Metrò", wild: "Funicolare" },
  { normal: "Ferrari", wild: "Lamborghini" },
  { normal: "Trattore", wild: "Ruspa" },

  // --- Professioni ---
  { normal: "Medico", wild: "Infermiere" },
  { normal: "Dentista", wild: "Chirurgo" },
  { normal: "Avvocato", wild: "Notaio" },
  { normal: "Pompiere", wild: "Poliziotto" },
  { normal: "Insegnante", wild: "Professore" },
  { normal: "Cuoco", wild: "Pasticcere" },
  { normal: "Cameriere", wild: "Barista" },
  { normal: "Meccanico", wild: "Idraulico" },
  { normal: "Muratore", wild: "Elettricista" },
  { normal: "Postino", wild: "Corriere" },
  { normal: "Parrucchiere", wild: "Estetista" },
  { normal: "Pilota", wild: "Capitano di nave" },
  { normal: "Attore", wild: "Cantante" },
  { normal: "Calciatore", wild: "Tennista" },
  { normal: "Agricoltore", wild: "Pescatore" },
  { normal: "Macellaio", wild: "Fornaio" },

  // --- Casa & Oggetti ---
  { normal: "Divano", wild: "Poltrona" },
  { normal: "Letto", wild: "Divano letto" },
  { normal: "Frigorifero", wild: "Congelatore" },
  { normal: "Forno", wild: "Microonde" },
  { normal: "Lavatrice", wild: "Lavastoviglie" },
  { normal: "Televisione", wild: "Proiettore" },
  { normal: "Lampada", wild: "Candela" },
  { normal: "Tappeto", wild: "Stuoia" },
  { normal: "Specchio", wild: "Quadro" },
  { normal: "Cuscino", wild: "Coperta" },
  { normal: "Scopa", wild: "Aspirapolvere" },
  { normal: "Forbici", wild: "Coltello" },
  { normal: "Martello", wild: "Cacciavite" },
  { normal: "Ombrello", wild: "Impermeabile" },
  { normal: "Sveglia", wild: "Orologio da muro" },
  { normal: "Padella", wild: "Pentola" },
  { normal: "Bicchiere", wild: "Tazza" },
  { normal: "Piatto", wild: "Ciotola" },
  { normal: "Forchetta", wild: "Cucchiaio" },

  // --- Igiene & Bagno ---
  { normal: "Shampoo", wild: "Balsamo" },
  { normal: "Sapone", wild: "Gel doccia" },
  { normal: "Dentifricio", wild: "Collutorio" },
  { normal: "Spazzolino", wild: "Filo interdentale" },
  { normal: "Asciugacapelli", wild: "Piastra per capelli" },
  { normal: "Doccia", wild: "Vasca da bagno" },
  { normal: "Rasoio", wild: "Crema depilatoria" },
  { normal: "Profumo", wild: "Deodorante" },

  // --- Abbigliamento ---
  { normal: "Felpa", wild: "Maglione" },
  { normal: "Giacca", wild: "Cappotto" },
  { normal: "Jeans", wild: "Pantaloni" },
  { normal: "Camicia", wild: "Polo" },
  { normal: "Maglietta", wild: "Canottiera" },
  { normal: "Gonna", wild: "Vestito" },
  { normal: "Sneakers", wild: "Stivali" },
  { normal: "Sandali", wild: "Infradito" },
  { normal: "Cappello", wild: "Berretto" },
  { normal: "Sciarpa", wild: "Guanti" },
  { normal: "Calzini", wild: "Calze" },
  { normal: "Pigiama", wild: "Vestaglia" },
  { normal: "Costume da bagno", wild: "Bikini" },
  { normal: "Cintura", wild: "Cravatta" },
  { normal: "Anello", wild: "Braccialetto" },
  { normal: "Collana", wild: "Orecchini" },
  { normal: "Occhiali da sole", wild: "Occhiali da vista" },
  { normal: "Zaino", wild: "Borsa" },
  { normal: "Portafoglio", wild: "Borsellino" },
  { normal: "Nike", wild: "Adidas" },

  // --- Scuola ---
  { normal: "Matematica", wild: "Fisica" },
  { normal: "Storia", wild: "Geografia" },
  { normal: "Italiano", wild: "Latino" },
  { normal: "Inglese", wild: "Francese" },
  { normal: "Scienze", wild: "Biologia" },
  { normal: "Arte", wild: "Musica" },
  { normal: "Educazione fisica", wild: "Educazione civica" },
  { normal: "Compito in classe", wild: "Interrogazione" },
  { normal: "Quaderno", wild: "Diario" },
  { normal: "Matita", wild: "Penna" },
  { normal: "Gomma", wild: "Temperamatite" },
  { normal: "Righello", wild: "Compasso" },
  { normal: "Zaino scolastico", wild: "Cartella" },
  { normal: "Libro di testo", wild: "Dizionario" },
  { normal: "Pennarello", wild: "Pastello" },
  { normal: "Liceo", wild: "Istituto tecnico" },
  { normal: "Preside", wild: "Professore" },
  { normal: "Gita scolastica", wild: "Ricreazione" },

  // --- Natura & Meteo ---
  { normal: "Sole", wild: "Luna" },
  { normal: "Pioggia", wild: "Temporale" },
  { normal: "Neve", wild: "Grandine" },
  { normal: "Vento", wild: "Nebbia" },
  { normal: "Arcobaleno", wild: "Stella cadente" },
  { normal: "Vulcano", wild: "Terremoto" },
  { normal: "Fiume", wild: "Torrente" },
  { normal: "Cascata", wild: "Sorgente" },
  { normal: "Spiaggia", wild: "Scogliera" },
  { normal: "Aurora boreale", wild: "Eclissi" },

  // --- Fiori & Piante ---
  { normal: "Rosa", wild: "Tulipano" },
  { normal: "Girasole", wild: "Margherita" },
  { normal: "Orchidea", wild: "Giglio" },
  { normal: "Cactus", wild: "Bambù" },
  { normal: "Pino", wild: "Quercia" },
  { normal: "Palma", wild: "Ulivo" },
  { normal: "Lavanda", wild: "Camomilla" },
  { normal: "Basilico", wild: "Prezzemolo" },
  { normal: "Rosmarino", wild: "Menta" },

  // --- Musica ---
  { normal: "Rock", wild: "Metal" },
  { normal: "Pop", wild: "Hip hop" },
  { normal: "Jazz", wild: "Blues" },
  { normal: "Reggae", wild: "Elettronica" },
  { normal: "Chitarra", wild: "Basso" },
  { normal: "Pianoforte", wild: "Tastiera" },
  { normal: "Batteria", wild: "Percussioni" },
  { normal: "Violino", wild: "Tromba" },
  { normal: "Sassofono", wild: "Clarinetto" },
  { normal: "Microfono", wild: "Cuffie" },
  { normal: "Concerto", wild: "Festival musicale" },
  { normal: "Vinile", wild: "CD" },

  // --- Giochi & Tempo libero ---
  { normal: "Scacchi", wild: "Dama" },
  { normal: "Monopoly", wild: "Risiko" },
  { normal: "Carte da gioco", wild: "Dadi" },
  { normal: "Puzzle", wild: "Memory" },
  { normal: "Calcetto", wild: "Biliardo" },
  { normal: "Bowling", wild: "Freccette" },
  { normal: "Campeggio", wild: "Pic nic" },
  { normal: "Barbecue", wild: "Pic nic" },
  { normal: "Videogioco", wild: "Gioco da tavolo" },

  // --- Feste & Ricorrenze ---
  { normal: "Compleanno", wild: "Onomastico" },
  { normal: "Natale", wild: "Capodanno" },
  { normal: "Pasqua", wild: "Carnevale" },
  { normal: "Halloween", wild: "Giorno dei Morti" },
  { normal: "San Valentino", wild: "Festa della mamma" },
  { normal: "Matrimonio", wild: "Fidanzamento" },
  { normal: "Laurea", wild: "Diploma" },
  { normal: "Battesimo", wild: "Cresima" },
  { normal: "Fuochi d'artificio", wild: "Torcia" },
  { normal: "Torta di compleanno", wild: "Torta nuziale" },
  { normal: "Regalo", wild: "Biglietto d'auguri" },
  { normal: "Ferragosto", wild: "Festa della Repubblica" },

  // --- Personaggi fantastici ---
  { normal: "Drago", wild: "Dinosauro" },
  { normal: "Strega", wild: "Fata" },
  { normal: "Vampiro", wild: "Fantasma" },
  { normal: "Elfo", wild: "Gnomo" },
  { normal: "Unicorno", wild: "Pegaso" },
  { normal: "Sirena", wild: "Mostro marino" },
  { normal: "Robot", wild: "Alieno" },
  { normal: "Mago", wild: "Stregone" },

  // --- Famiglia & Persone ---
  { normal: "Nonno", wild: "Zio" },
  { normal: "Cugino", wild: "Cognato" },
  { normal: "Fidanzato", wild: "Marito" },
  { normal: "Migliore amico", wild: "Compagno di classe" },
  { normal: "Vicino di casa", wild: "Coinquilino" },
  { normal: "Babysitter", wild: "Tata" },

  // --- Colori ---
  { normal: "Rosso", wild: "Rosa" },
  { normal: "Blu", wild: "Azzurro" },
  { normal: "Verde", wild: "Verde chiaro" },
  { normal: "Giallo", wild: "Arancione" },
  { normal: "Nero", wild: "Grigio" },
  { normal: "Bianco", wild: "Beige" },
  { normal: "Viola", wild: "Lilla" },
  { normal: "Marrone", wild: "Nocciola" },

  // --- Vacanze ---
  { normal: "Vacanza al mare", wild: "Vacanza in montagna" },
  { normal: "Albergo", wild: "Campeggio" },
  { normal: "Valigia", wild: "Zaino da viaggio" },
  { normal: "Passaporto", wild: "Carta d'identità" },
  { normal: "Ombrellone", wild: "Sdraio" },
  { normal: "Pinne", wild: "Maschera subacquea" },
  { normal: "Pedalò", wild: "Canotto" },
  { normal: "Souvenir", wild: "Cartolina" },
  { normal: "Aereo", wild: "Nave da crociera" },
  { normal: "Tour guidato", wild: "Viaggio da soli" },

  // --- Giochi da bambini & Attività ---
  { normal: "Nascondino", wild: "Guardie e ladri" },
  { normal: "Salto con la corda", wild: "Elastico" },
  { normal: "Altalena", wild: "Scivolo" },
  { normal: "Pallone", wild: "Frisbee" },
  { normal: "Aquilone", wild: "Boomerang" },
  { normal: "Sabbietta al parco", wild: "Piscina gonfiabile" },
  { normal: "Biciclettina", wild: "Triciclo" },
  { normal: "Pattini", wild: "Monopattino" },
  { normal: "Biglie", wild: "Trottola" },
  { normal: "Costruzioni", wild: "Plastilina" },
  { normal: "Puzzle", wild: "Domino" },
  { normal: "Palloncino", wild: "Coriandoli" },
  { normal: "Bolle di sapone", wild: "Pistola ad acqua" },
  { normal: "Yo-yo", wild: "Girandola" },

  // --- Scuola (vita quotidiana) ---
  { normal: "Intervallo", wild: "Gita scolastica" },
  { normal: "Bidello", wild: "Segretaria scolastica" },
  { normal: "Zaino pesante", wild: "Cartella" },
  { normal: "Banco", wild: "Cattedra" },
  { normal: "Lavagna", wild: "LIM" },
  { normal: "Campanella", wild: "Sirena" },
  { normal: "Pagella", wild: "Voto" },
  { normal: "Bocciatura", wild: "Rimandato" },
  { normal: "Mensa scolastica", wild: "Panino da casa" },

  // --- Casa (stanze & spazi) ---
  { normal: "Cucina", wild: "Bagno" },
  { normal: "Salotto", wild: "Camera da letto" },
  { normal: "Garage", wild: "Cantina" },
  { normal: "Terrazzo", wild: "Giardino" },
  { normal: "Scala", wild: "Ascensore" },
  { normal: "Portone", wild: "Cancello" },
  { normal: "Mansarda", wild: "Seminterrato" },
  { normal: "Corridoio", wild: "Ingresso" },

  // --- Animali domestici ---
  { normal: "Cane da compagnia", wild: "Gatto domestico" },
  { normal: "Criceto", wild: "Porcellino d'India" },
  { normal: "Tartaruga di terra", wild: "Tartaruga d'acqua" },
  { normal: "Pesciolino rosso", wild: "Pesce tropicale" },
  { normal: "Coniglio nano", wild: "Coniglio angora" },
  { normal: "Pappagallino", wild: "Canarino" },
  { normal: "Furetto", wild: "Cincillà" },

  // --- Tempo libero & Hobby ---
  { normal: "Leggere un libro", wild: "Leggere un fumetto" },
  { normal: "Disegnare", wild: "Colorare" },
  { normal: "Cucinare", wild: "Fare dolci" },
  { normal: "Guardare la TV", wild: "Guardare film al cinema" },
  { normal: "Fare una passeggiata", wild: "Fare jogging" },
  { normal: "Giocare a carte", wild: "Giocare a dadi" },
  { normal: "Fare fotografie", wild: "Fare video" },
  { normal: "Cantare sotto la doccia", wild: "Cantare al karaoke" },
  { normal: "Ballare", wild: "Fare yoga" },
  { normal: "Fare giardinaggio", wild: "Raccogliere funghi" },
  { normal: "Pescare", wild: "Cacciare" },
  { normal: "Fare puzzle", wild: "Fare cruciverba" },
  { normal: "Collezionare figurine", wild: "Collezionare monete" },
  { normal: "Fare escursioni", wild: "Fare trekking" },

  // --- Supermercato (prodotti comuni) ---
  { normal: "Latte intero", wild: "Latte scremato" },
  { normal: "Uova", wild: "Uova di quaglia" },
  { normal: "Farina", wild: "Semola" },
  { normal: "Zucchero", wild: "Miele" },
  { normal: "Sale", wild: "Pepe" },
  { normal: "Olio di oliva", wild: "Olio di semi" },
  { normal: "Pasta corta", wild: "Pasta lunga" },
  { normal: "Riso", wild: "Farro" },
  { normal: "Pane in cassetta", wild: "Pane di segale" },
  { normal: "Burro", wild: "Strutto" },
  { normal: "Panna da cucina", wild: "Panna da montare" },
  { normal: "Brodo in dado", wild: "Brodo in brik" },
  { normal: "Pelati", wild: "Passata di pomodoro" },
  { normal: "Piselli in scatola", wild: "Mais in scatola" },
  { normal: "Merendina", wild: "Crackers" },
  { normal: "Succo di frutta", wild: "Centrifugato" },
  { normal: "Acqua in bottiglia", wild: "Acqua del rubinetto" },
  { normal: "Caffè macinato", wild: "Caffè in cialde" },
  { normal: "Detersivo per piatti", wild: "Detersivo per bucato" },
  { normal: "Carta igienica", wild: "Carta da cucina" },
  { normal: "Sacchetti della spazzatura", wild: "Sacchetti per la spesa" },

  // --- Meteo & Stagioni ---
  { normal: "Estate", wild: "Primavera" },
  { normal: "Autunno", wild: "Inverno" },
  { normal: "Giornata di sole", wild: "Giornata nuvolosa" },
  { normal: "Ombrello", wild: "Impermeabile" },
  { normal: "Stivali da pioggia", wild: "Scarpe impermeabili" },
  { normal: "Giubbotto invernale", wild: "Giacca a vento" },
  { normal: "Sciarpa", wild: "Passamontagna" },
  { normal: "Crema solare", wild: "Doposole" },
  { normal: "Ventilatore", wild: "Condizionatore" },
  { normal: "Termosifone", wild: "Stufa" },
  { normal: "Coperta di pile", wild: "Plaid" },

  // --- Mezzi di comunicazione ---
  { normal: "Telefonata", wild: "Videochiamata" },
  { normal: "SMS", wild: "Messaggio vocale" },
  { normal: "Email", wild: "Lettera cartacea" },
  { normal: "Giornale cartaceo", wild: "Giornale online" },
  { normal: "Radio", wild: "Podcast" },
  { normal: "Telegiornale", wild: "Notizie online" },
  { normal: "Manifesto", wild: "Volantino" },
  { normal: "Cartolina", wild: "Bigliettino" },

  // --- Ristorante & Bar (situazioni) ---
  { normal: "Ordinare al cameriere", wild: "Ordinare al banco" },
  { normal: "Menu cartaceo", wild: "QR code del menu" },
  { normal: "Conto da pagare", wild: "Scontrino" },
  { normal: "Mancia", wild: "Coperto" },
  { normal: "Tavolo prenotato", wild: "Lista d'attesa" },
  { normal: "Tovagliolo di carta", wild: "Tovagliolo di stoffa" },
  { normal: "Acqua del rubinetto al bar", wild: "Acqua in bottiglia al bar" },
  { normal: "Aperitivo", wild: "Digestivo" },
  { normal: "Antipasto", wild: "Secondo piatto" },
  { normal: "Dessert", wild: "Caffè finale" },

  // --- Ospedale & Salute ---
  { normal: "Visita dal medico", wild: "Visita specialistica" },
  { normal: "Puntura di vaccino", wild: "Analisi del sangue" },
  { normal: "Sala d'attesa", wild: "Pronto soccorso" },
  { normal: "Ricetta medica", wild: "Impegnativa" },
  { normal: "Cerotto", wild: "Benda" },
  { normal: "Sciroppo per la tosse", wild: "Spray nasale" },
  { normal: "Mal di pancia", wild: "Nausea" },
  { normal: "Mal di gola", wild: "Raucedine" },
  { normal: "Raffreddore", wild: "Influenza" },
  { normal: "Febbre alta", wild: "Febbricola" },
  { normal: "Ghiaccio sulla botta", wild: "Pomata antidolore" },

  // --- Viaggio & Vacanza (situazioni) ---
  { normal: "Fare le valigie", wild: "Preparare il bagaglio a mano" },
  { normal: "Perdere l'aereo", wild: "Ritardo del treno" },
  { normal: "Check-in in hotel", wild: "Check-out dall'hotel" },
  { normal: "Camera doppia", wild: "Camera singola" },
  { normal: "Colazione inclusa", wild: "Mezza pensione" },
  { normal: "Mappa cartacea", wild: "GPS sul telefono" },
  { normal: "Cambio valuta", wild: "Bancomat all'estero" },
  { normal: "Dogana", wild: "Controllo passaporti" },
  { normal: "Turista", wild: "Viaggiatore" },
  { normal: "Foto ricordo", wild: "Selfie" },

  // --- Oggetti di uso quotidiano ---
  { normal: "Chiavi di casa", wild: "Chiavi della macchina" },
  { normal: "Portafoglio", wild: "Borsellino" },
  { normal: "Occhiali da sole", wild: "Occhiali da lettura" },
  { normal: "Cuffie", wild: "Auricolari" },
  { normal: "Caricabatterie", wild: "Powerbank" },
  { normal: "Agenda cartacea", wild: "Calendario sul telefono" },
  { normal: "Penna a sfera", wild: "Matita" },
  { normal: "Accendino", wild: "Fiammiferi" },
  { normal: "Orologio da polso", wild: "Orologio da taschino" },
  { normal: "Ombrello piccolo", wild: "Ombrello grande" },
  { normal: "Borsa della spesa", wild: "Zaino" },
  { normal: "Valigia con rotelle", wild: "Borsone da viaggio" },

  // --- Sport (situazioni & luoghi) ---
  { normal: "Campo da calcio", wild: "Campo da basket" },
  { normal: "Spogliatoio", wild: "Campo di allenamento" },
  { normal: "Arbitro", wild: "Allenatore" },
  { normal: "Tifoso allo stadio", wild: "Tifoso davanti alla TV" },
  { normal: "Maglietta della squadra", wild: "Sciarpa della squadra" },
  { normal: "Pallone da calcio", wild: "Pallone da basket" },
  { normal: "Scarpe da calcio", wild: "Scarpe da ginnastica" },
  { normal: "Medaglia d'oro", wild: "Medaglia d'argento" },
  { normal: "Coppa del mondo", wild: "Campionato europeo" },
  { normal: "Partita in casa", wild: "Partita in trasferta" },
  { normal: "Gol", wild: "Rigore" },
  { normal: "Fallo", wild: "Cartellino giallo" },
  { normal: "Portiere", wild: "Attaccante" },
  { normal: "Difensore", wild: "Centrocampista" },

  // --- Feste (oggetti & attività) ---
  { normal: "Candeline sulla torta", wild: "Fiaccole da giardino" },
  { normal: "Palloncini", wild: "Stelle filanti" },
  { normal: "Carta da regalo", wild: "Sacchettino regalo" },
  { normal: "Nastro da regalo", wild: "Fiocco" },
  { normal: "Buffet", wild: "Cena seduta" },
  { normal: "Discoteca", wild: "Festa in casa" },
  { normal: "DJ", wild: "Band dal vivo" },
  { normal: "Invito cartaceo", wild: "Invito digitale" },
  { normal: "Foto di gruppo", wild: "Video ricordo" },
  { normal: "Brindisi con champagne", wild: "Brindisi con succo" },

  // --- Personaggi delle favole (nuovi) ---
  { normal: "Babbo Natale", wild: "Befana" },
  { normal: "Fatina del dente", wild: "Uomo dei sogni" },
  { normal: "Il lupo cattivo", wild: "L'orco" },
  { normal: "Il principe azzurro", wild: "Il cavaliere" },
  { normal: "La matrigna cattiva", wild: "La strega della mela" },
  { normal: "Mago", wild: "Stregone" },
  { normal: "Nano", wild: "Gnomo" },
  { normal: "Gigante", wild: "Mostro" },

  // --- Città italiane & luoghi famosi ---
  { normal: "Colosseo", wild: "Pantheon" },
  { normal: "Torre di Pisa", wild: "Torre di Belem" },
  { normal: "Duomo di Milano", wild: "Duomo di Firenze" },
  { normal: "Canal Grande", wild: "Ponte di Rialto" },
  { normal: "Vesuvio", wild: "Etna" },
  { normal: "Portofino", wild: "Cinque Terre" },
  { normal: "Lago di Como", wild: "Lago di Garda" },
  { normal: "Dolomiti", wild: "Appennini" },
  { normal: "Riviera romagnola", wild: "Costiera amalfitana" },
  { normal: "Piazza Navona", wild: "Piazza di Spagna" },

  // --- Oggetti della cucina ---
  { normal: "Padella antiaderente", wild: "Padella in ghisa" },
  { normal: "Pentola grande", wild: "Casseruola" },
  { normal: "Tagliere di legno", wild: "Tagliere di plastica" },
  { normal: "Coltello da cucina", wild: "Coltellino da frutta" },
  { normal: "Apriscatole", wild: "Cavatappi" },
  { normal: "Colino", wild: "Scolapasta" },
  { normal: "Mestolo", wild: "Spatola" },
  { normal: "Mattarello", wild: "Stampo per biscotti" },
  { normal: "Frullatore", wild: "Frullino a mano" },
  { normal: "Tostapane", wild: "Forno elettrico" },
  { normal: "Moka", wild: "Macchina del caffè" },
  { normal: "Bollitore", wild: "Termos" },
  { normal: "Contenitore per il cibo", wild: "Sacchetto zip" },
  { normal: "Pellicola trasparente", wild: "Carta stagnola" },

  // --- Vestiti (situazioni) ---
  { normal: "Vestirsi elegante", wild: "Vestirsi casual" },
  { normal: "Cambiarsi dopo il lavoro", wild: "Indossare il pigiama" },
  { normal: "Lavarsi i panni", wild: "Portare in lavanderia" },
  { normal: "Stirare la camicia", wild: "Sgualcire la camicia" },
  { normal: "Comprare scarpe nuove", wild: "Risuolare le vecchie" },
  { normal: "Togliersi le scarpe in casa", wild: "Tenere le scarpe in casa" },

  // --- Mezzi di pagamento ---
  { normal: "Pagare in contanti", wild: "Pagare con il bancomat" },
  { normal: "Scontrino", wild: "Ricevuta" },
  { normal: "Carta di credito", wild: "Carta prepagata" },
  { normal: "Portafoglio pieno", wild: "Portafoglio vuoto" },
  { normal: "Resto in monete", wild: "Resto in banconote" },

  // --- Natura (elementi semplici) ---
  { normal: "Pietra", wild: "Ciottolo" },
  { normal: "Ramo", wild: "Ramoscello" },
  { normal: "Foglia", wild: "Aghi di pino" },
  { normal: "Fiore di campo", wild: "Fiore da vaso" },
  { normal: "Fungo nel bosco", wild: "Fungo coltivato" },
  { normal: "Conchiglia", wild: "Corallo" },
  { normal: "Nido d'uccello", wild: "Tana di coniglio" },
  { normal: "Pozzanghera", wild: "Ruscello" },
  { normal: "Tramonto", wild: "Alba" },
  { normal: "Cielo stellato", wild: "Cielo nuvoloso" },
  { normal: "Luna piena", wild: "Luna crescente" },

];
