// ============================================================
//  PAROLE.JS — Database parole per il gioco Impostore
//  Aggiungi quante coppie vuoi seguendo il formato:
//  { normal: "Parola normale", wild: "Parola di Mister Wild" }
// ============================================================

const WORD_PAIRS = [

  // --- App & Social ---
  { normal: "Instagram", wild: "Facebook" },
  { normal: "WhatsApp", wild: "Telegram" },
  { normal: "Netflix", wild: "Disney+" },
  { normal: "YouTube", wild: "TikTok" },
  { normal: "Spotify", wild: "Apple Music" },
  { normal: "iPhone", wild: "Samsung Galaxy" },
  { normal: "PlayStation", wild: "Xbox" },
  { normal: "Amazon", wild: "eBay" },
  { normal: "Google Maps", wild: "Waze" },
  { normal: "McDonald's", wild: "Burger King" },

  // --- Film & Cartoni ---
  { normal: "Harry Potter", wild: "Il Signore degli Anelli" },
  { normal: "Il Re Leone", wild: "Dumbo" },
  { normal: "Shrek", wild: "Kung Fu Panda" },
  { normal: "Toy Story", wild: "Cars" },
  { normal: "Frozen", wild: "Rapunzel" },
  { normal: "Cenerentola", wild: "Biancaneve" },
  { normal: "Pinocchio", wild: "Pollicino" },
  { normal: "Aladdin", wild: "La Bella e la Bestia" },
  { normal: "Titanic", wild: "Il Gladiatore" },
  { normal: "Spider-Man", wild: "Batman" },
  { normal: "Jurassic Park", wild: "King Kong" },
  { normal: "La Casa di Carta", wild: "Squid Game" },
  { normal: "Naruto", wild: "Dragon Ball" },
  { normal: "Forrest Gump", wild: "Cast Away" },
  { normal: "Indiana Jones", wild: "James Bond" },
  { normal: "Cappuccetto Rosso", wild: "Hansel e Gretel" },
  { normal: "Superman", wild: "Batman" },
  { normal: "Topolino", wild: "Paperino" },
  { normal: "Asterix", wild: "Obelix" },
  { normal: "Dracula", wild: "Frankenstein" },

  // --- Cibo ---
  { normal: "Pizza", wild: "Focaccia" },
  { normal: "Hamburger", wild: "Hot dog" },
  { normal: "Gelato", wild: "Sorbetto" },
  { normal: "Pasta al pomodoro", wild: "Pasta in bianco" },
  { normal: "Lasagne", wild: "Pasta al forno" },
  { normal: "Patatine fritte", wild: "Patatine al forno" },
  { normal: "Carbonara", wild: "Amatriciana" },
  { normal: "Ravioli", wild: "Tortellini" },
  { normal: "Risotto", wild: "Minestra" },
  { normal: "Polpette", wild: "Cotoletta" },
  { normal: "Bistecca", wild: "Pollo arrosto" },
  { normal: "Prosciutto", wild: "Mortadella" },
  { normal: "Mozzarella", wild: "Ricotta" },
  { normal: "Salame", wild: "Mortadella" },
  { normal: "Panino", wild: "Tramezzino" },
  { normal: "Pane", wild: "Grissino" },
  { normal: "Uovo", wild: "Frittata" },
  { normal: "Frittata", wild: "Omelette" },
  { normal: "Insalata", wild: "Verdure" },
  { normal: "Gamberetti", wild: "Calamari" },
  { normal: "Cozze", wild: "Vongole" },
  { normal: "Sushi", wild: "Kebab" },
  { normal: "Pesto", wild: "Ragù" },
  { normal: "Maionese", wild: "Ketchup" },

  // --- Dolci & Colazione ---
  { normal: "Tiramisù", wild: "Panna cotta" },
  { normal: "Cornetto", wild: "Brioche" },
  { normal: "Nutella", wild: "Marmellata" },
  { normal: "Biscotti", wild: "Wafer" },
  { normal: "Torta", wild: "Crostata" },
  { normal: "Cioccolato", wild: "Caramella" },
  { normal: "Caramella", wild: "Gomma da masticare" },
  { normal: "Panettone", wild: "Pandoro" },
  { normal: "Granita", wild: "Frappè" },
  { normal: "Kinder Bueno", wild: "Kinder Cereali" },
  { normal: "Oreo", wild: "Ringo" },

  // --- Bevande ---
  { normal: "Coca-Cola", wild: "Pepsi" },
  { normal: "Fanta", wild: "Sprite" },
  { normal: "Cappuccino", wild: "Macchiato" },
  { normal: "Caffè", wild: "Espresso" },
  { normal: "Cioccolata", wild: "Cacao" },
  { normal: "Tè", wild: "Infuso" },
  { normal: "Acqua", wild: "Bibita" },
  { normal: "Birra", wild: "Vino" },
  { normal: "Vino rosso", wild: "Vino bianco" },
  { normal: "Prosecco", wild: "Champagne" },
  { normal: "Yogurt", wild: "Latte" },

  // --- Frutta ---
  { normal: "Mela", wild: "Pera" },
  { normal: "Arancia", wild: "Mandarino" },
  { normal: "Fragola", wild: "Lampone" },
  { normal: "Uva", wild: "Mirtillo" },
  { normal: "Limone", wild: "Lime" },
  { normal: "Anguria", wild: "Melone" },
  { normal: "Pesca", wild: "Albicocca" },
  { normal: "Ciliegia", wild: "Susina" },
  { normal: "Kiwi", wild: "Mango" },
  { normal: "Ananas", wild: "Papaya" },
  { normal: "Banana", wild: "Mango" },
  { normal: "Noce", wild: "Nocciola" },
  { normal: "Mandorla", wild: "Pistacchio" },
  { normal: "Castagna", wild: "Noce" },

  // --- Verdura ---
  { normal: "Pomodoro", wild: "Peperone" },
  { normal: "Zucchina", wild: "Melanzana" },
  { normal: "Carota", wild: "Patata" },
  { normal: "Insalata", wild: "Spinaci" },
  { normal: "Cipolla", wild: "Aglio" },
  { normal: "Fagioli", wild: "Piselli" },
  { normal: "Funghi", wild: "Carciofi" },
  { normal: "Mais", wild: "Grano" },

  // --- Animali comuni ---
  { normal: "Cane", wild: "Gatto" },
  { normal: "Leone", wild: "Tigre" },
  { normal: "Elefante", wild: "Rinoceronte" },
  { normal: "Delfino", wild: "Balena" },
  { normal: "Aquila", wild: "Falco" },
  { normal: "Coniglio", wild: "Criceto" },
  { normal: "Squalo", wild: "Polpo" },
  { normal: "Coccodrillo", wild: "Alligatore" },
  { normal: "Serpente", wild: "Lucertola" },
  { normal: "Tartaruga", wild: "Lumaca" },
  { normal: "Cavallo", wild: "Asino" },
  { normal: "Mucca", wild: "Pecora" },
  { normal: "Maiale", wild: "Cinghiale" },
  { normal: "Gallina", wild: "Tacchino" },
  { normal: "Oca", wild: "Anatra" },
  { normal: "Pinguino", wild: "Foca" },
  { normal: "Orso", wild: "Lupo" },
  { normal: "Volpe", wild: "Lepre" },
  { normal: "Gorilla", wild: "Scimpanzé" },
  { normal: "Giraffa", wild: "Zebra" },
  { normal: "Cammello", wild: "Lama" },
  { normal: "Pappagallo", wild: "Canarino" },
  { normal: "Piccione", wild: "Rondine" },
  { normal: "Ape", wild: "Farfalla" },
  { normal: "Ragno", wild: "Formica" },
  { normal: "Rana", wild: "Rospo" },
  { normal: "Topo", wild: "Ratto" },

  // --- Sport ---
  { normal: "Calcio", wild: "Rugby" },
  { normal: "Tennis", wild: "Padel" },
  { normal: "Nuoto", wild: "Pallanuoto" },
  { normal: "Basket", wild: "Pallavolo" },
  { normal: "Sci", wild: "Snowboard" },
  { normal: "Boxe", wild: "Karate" },
  { normal: "Formula 1", wild: "MotoGP" },
  { normal: "Ciclismo", wild: "Corsa a piedi" },
  { normal: "Golf", wild: "Minigolf" },
  { normal: "Ping pong", wild: "Badminton" },
  { normal: "Judo", wild: "Lotta" },
  { normal: "Surf", wild: "Sci d'acqua" },
  { normal: "Pattinaggio", wild: "Skateboard" },
  { normal: "Ginnastica", wild: "Danza sportiva" },
  { normal: "Baseball", wild: "Cricket" },
  { normal: "Hockey", wild: "Curling" },
  { normal: "Maratona", wild: "Triathlon" },

  // --- Luoghi ---
  { normal: "Spiaggia", wild: "Piscina" },
  { normal: "Montagna", wild: "Collina" },
  { normal: "Parco", wild: "Giardino" },
  { normal: "Supermercato", wild: "Mercato" },
  { normal: "Ospedale", wild: "Farmacia" },
  { normal: "Chiesa", wild: "Municipio" },
  { normal: "Castello", wild: "Torre" },
  { normal: "Zoo", wild: "Acquario" },
  { normal: "Cinema", wild: "Teatro" },
  { normal: "Ristorante", wild: "Pizzeria" },
  { normal: "Bar", wild: "Gelateria" },
  { normal: "Palestra", wild: "Piscina" },
  { normal: "Discoteca", wild: "Pub" },
  { normal: "Stadio", wild: "Palazzetto" },
  { normal: "Biblioteca", wild: "Libreria" },
  { normal: "Aeroporto", wild: "Stazione" },
  { normal: "Scuola", wild: "Università" },
  { normal: "Parrucchiere", wild: "Barbiere" },
  { normal: "Banca", wild: "Ufficio postale" },
  { normal: "Pizzeria", wild: "Braceria" },
  { normal: "Roma", wild: "Milano" },
  { normal: "Napoli", wild: "Palermo" },
  { normal: "Firenze", wild: "Venezia" },
  { normal: "Londra", wild: "Parigi" },
  { normal: "New York", wild: "Los Angeles" },
  { normal: "Mare", wild: "Lago" },
  { normal: "Foresta", wild: "Giungla" },
  { normal: "Deserto", wild: "Savana" },
  { normal: "Isola", wild: "Penisola" },

  // --- Trasporti ---
  { normal: "Aereo", wild: "Elicottero" },
  { normal: "Treno", wild: "Tram" },
  { normal: "Bicicletta", wild: "Monopattino" },
  { normal: "Taxi", wild: "Bus" },
  { normal: "Nave", wild: "Traghetto" },
  { normal: "Ambulanza", wild: "Polizia" },
  { normal: "Camion", wild: "Furgone" },
  { normal: "Moto", wild: "Vespa" },
  { normal: "Macchina", wild: "SUV" },
  { normal: "Metrò", wild: "Funicolare" },
  { normal: "Ferrari", wild: "Lamborghini" },
  { normal: "Trattore", wild: "Ruspa" },

  // --- Professioni ---
  { normal: "Medico", wild: "Infermiere" },
  { normal: "Dentista", wild: "Chirurgo" },
  { normal: "Avvocato", wild: "Notaio" },
  { normal: "Pompiere", wild: "Poliziotto" },
  { normal: "Insegnante", wild: "Professore" },
  { normal: "Cuoco", wild: "Pasticcere" },
  { normal: "Cameriere", wild: "Barista" },
  { normal: "Meccanico", wild: "Idraulico" },
  { normal: "Muratore", wild: "Elettricista" },
  { normal: "Postino", wild: "Corriere" },
  { normal: "Parrucchiere", wild: "Estetista" },
  { normal: "Pilota", wild: "Capitano di nave" },
  { normal: "Attore", wild: "Cantante" },
  { normal: "Calciatore", wild: "Tennista" },
  { normal: "Agricoltore", wild: "Pescatore" },
  { normal: "Macellaio", wild: "Fornaio" },

  // --- Casa & Oggetti ---
  { normal: "Divano", wild: "Poltrona" },
  { normal: "Letto", wild: "Divano letto" },
  { normal: "Frigorifero", wild: "Congelatore" },
  { normal: "Forno", wild: "Microonde" },
  { normal: "Lavatrice", wild: "Lavastoviglie" },
  { normal: "Televisione", wild: "Proiettore" },
  { normal: "Lampada", wild: "Candela" },
  { normal: "Tappeto", wild: "Stuoia" },
  { normal: "Specchio", wild: "Quadro" },
  { normal: "Cuscino", wild: "Coperta" },
  { normal: "Scopa", wild: "Aspirapolvere" },
  { normal: "Forbici", wild: "Coltello" },
  { normal: "Martello", wild: "Cacciavite" },
  { normal: "Ombrello", wild: "Impermeabile" },
  { normal: "Sveglia", wild: "Orologio da muro" },
  { normal: "Padella", wild: "Pentola" },
  { normal: "Bicchiere", wild: "Tazza" },
  { normal: "Piatto", wild: "Ciotola" },
  { normal: "Forchetta", wild: "Cucchiaio" },

  // --- Igiene & Bagno ---
  { normal: "Shampoo", wild: "Balsamo" },
  { normal: "Sapone", wild: "Gel doccia" },
  { normal: "Dentifricio", wild: "Collutorio" },
  { normal: "Spazzolino", wild: "Filo interdentale" },
  { normal: "Asciugacapelli", wild: "Piastra per capelli" },
  { normal: "Doccia", wild: "Vasca da bagno" },
  { normal: "Rasoio", wild: "Crema depilatoria" },
  { normal: "Profumo", wild: "Deodorante" },

  // --- Abbigliamento ---
  { normal: "Felpa", wild: "Maglione" },
  { normal: "Giacca", wild: "Cappotto" },
  { normal: "Jeans", wild: "Pantaloni" },
  { normal: "Camicia", wild: "Polo" },
  { normal: "Maglietta", wild: "Canottiera" },
  { normal: "Gonna", wild: "Vestito" },
  { normal: "Sneakers", wild: "Stivali" },
  { normal: "Sandali", wild: "Infradito" },
  { normal: "Cappello", wild: "Berretto" },
  { normal: "Sciarpa", wild: "Guanti" },
  { normal: "Calzini", wild: "Calze" },
  { normal: "Pigiama", wild: "Vestaglia" },
  { normal: "Costume", wild: "Bikini" },
  { normal: "Cintura", wild: "Cravatta" },
  { normal: "Anello", wild: "Braccialetto" },
  { normal: "Collana", wild: "Orecchini" },
  { normal: "Zaino", wild: "Borsa" },
  { normal: "Portafoglio", wild: "Borsellino" },
  { normal: "Nike", wild: "Adidas" },

  // --- Scuola ---
  { normal: "Matematica", wild: "Fisica" },
  { normal: "Storia", wild: "Geografia" },
  { normal: "Italiano", wild: "Latino" },
  { normal: "Inglese", wild: "Francese" },
  { normal: "Scienze", wild: "Biologia" },
  { normal: "Arte", wild: "Musica" },
  { normal: "Educazione Fisica", wild: "EducazioneCivica" },
  { normal: "Compito", wild: "Interrogazione" },
  { normal: "Quaderno", wild: "Diario" },
  { normal: "Matita", wild: "Penna" },
  { normal: "Gomma", wild: "Temperamatite" },
  { normal: "Righello", wild: "Compasso" },
  { normal: "Zaino", wild: "Cartella" },
  { normal: "Libro", wild: "Dizionario" },
  { normal: "Pennarello", wild: "Pastello" },
  { normal: "Liceo", wild: "Istituto tecnico" },
  { normal: "Preside", wild: "Professore" },
  { normal: "Gita", wild: "Ricreazione" },

  // --- Natura & Meteo ---
  { normal: "Sole", wild: "Luna" },
  { normal: "Pioggia", wild: "Temporale" },
  { normal: "Neve", wild: "Grandine" },
  { normal: "Vento", wild: "Nebbia" },
  { normal: "Arcobaleno", wild: "Stella cadente" },
  { normal: "Vulcano", wild: "Terremoto" },
  { normal: "Fiume", wild: "Torrente" },
  { normal: "Cascata", wild: "Sorgente" },
  { normal: "Spiaggia", wild: "Scogliera" },
  { normal: "Aurora boreale", wild: "Eclissi" },

  // --- Fiori & Piante ---
  { normal: "Rosa", wild: "Tulipano" },
  { normal: "Girasole", wild: "Margherita" },
  { normal: "Orchidea", wild: "Giglio" },
  { normal: "Cactus", wild: "Bambù" },
  { normal: "Pino", wild: "Quercia" },
  { normal: "Palma", wild: "Ulivo" },
  { normal: "Lavanda", wild: "Camomilla" },
  { normal: "Basilico", wild: "Prezzemolo" },
  { normal: "Rosmarino", wild: "Menta" },

  // --- Musica ---
  { normal: "Rock", wild: "Metal" },
  { normal: "Pop", wild: "Hip hop" },
  { normal: "Jazz", wild: "Blues" },
  { normal: "Reggae", wild: "Elettronica" },
  { normal: "Chitarra", wild: "Basso" },
  { normal: "Pianoforte", wild: "Tastiera" },
  { normal: "Batteria", wild: "Percussioni" },
  { normal: "Violino", wild: "Tromba" },
  { normal: "Sassofono", wild: "Clarinetto" },
  { normal: "Microfono", wild: "Cuffie" },
  { normal: "Concerto", wild: "Festival musicale" },
  { normal: "Vinile", wild: "CD" },

  // --- Giochi & Tempo libero ---
  { normal: "Scacchi", wild: "Dama" },
  { normal: "Monopoly", wild: "Risiko" },
  { normal: "Carte", wild: "Dadi" },
  { normal: "Puzzle", wild: "Memory" },
  { normal: "Calcetto", wild: "Biliardo" },
  { normal: "Bowling", wild: "Freccette" },
  { normal: "Campeggio", wild: "Pic nic" },
  { normal: "Barbecue", wild: "Pic nic" },
  { normal: "Videogioco", wild: "Gioco da tavolo" },

  // --- Feste & Ricorrenze ---
  { normal: "Compleanno", wild: "Onomastico" },
  { normal: "Natale", wild: "Capodanno" },
  { normal: "Pasqua", wild: "Carnevale" },
  { normal: "Halloween", wild: "Giorno dei Morti" },
  { normal: "San Valentino", wild: "Festa della mamma" },
  { normal: "Matrimonio", wild: "Fidanzamento" },
  { normal: "Laurea", wild: "Diploma" },
  { normal: "Battesimo", wild: "Cresima" },
  { normal: "Fuochi", wild: "Torcia" },
  { normal: "Torta", wild: "Dolce" },
  { normal: "Regalo", wild: "Biglietto d'auguri" },
  { normal: "Ferragosto", wild: "Festa della Repubblica" },

  // --- Personaggi fantastici ---
  { normal: "Drago", wild: "Dinosauro" },
  { normal: "Strega", wild: "Fata" },
  { normal: "Vampiro", wild: "Fantasma" },
  { normal: "Elfo", wild: "Gnomo" },
  { normal: "Unicorno", wild: "Pegaso" },
  { normal: "Sirena", wild: "Mostro marino" },
  { normal: "Robot", wild: "Alieno" },
  { normal: "Mago", wild: "Stregone" },

  // --- Famiglia & Persone ---
  { normal: "Nonno", wild: "Zio" },
  { normal: "Cugino", wild: "Cognato" },
  { normal: "Fidanzato", wild: "Marito" },
  { normal: "Vicino", wild: "Coinquilino" },
  { normal: "Babysitter", wild: "Tata" },

  // --- Colori ---
  { normal: "Rosso", wild: "Rosa" },
  { normal: "Blu", wild: "Azzurro" },
  { normal: "Verde", wild: "Verde chiaro" },
  { normal: "Giallo", wild: "Arancione" },
  { normal: "Nero", wild: "Grigio" },
  { normal: "Bianco", wild: "Beige" },
  { normal: "Viola", wild: "Lilla" },
  { normal: "Marrone", wild: "Nocciola" },

  // --- Vacanze ---
  { normal: "Vacanza al mare", wild: "Vacanza in montagna" },
  { normal: "Albergo", wild: "Campeggio" },
  { normal: "Valigia", wild: "Zaino da viaggio" },
  { normal: "Ombrellone", wild: "Sdraio" },
  { normal: "Pinne", wild: "Maschera subacquea" },
  { normal: "Pedalò", wild: "Canotto" },
  { normal: "Souvenir", wild: "Cartolina" },
  { normal: "Aereo", wild: "Nave da crociera" },

  // --- Giochi da bambini & Attività ---
  { normal: "Nascondino", wild: "Guardie e ladri" },
  { normal: "Altalena", wild: "Scivolo" },
  { normal: "Pallone", wild: "Frisbee" },
  { normal: "Aquilone", wild: "Boomerang" },
  { normal: "Pattini", wild: "Monopattino" },
  { normal: "Biglie", wild: "Trottola" },
  { normal: "Costruzioni", wild: "Plastilina" },
  { normal: "Puzzle", wild: "Domino" },
  { normal: "Palloncino", wild: "Coriandoli" },
  { normal: "Yo-yo", wild: "Girandola" },

  // --- Scuola (vita quotidiana) ---
  { normal: "Intervallo", wild: "Ricreazione" },
  { normal: "Bidello", wild: "Segretaria" },
  { normal: "Zaino", wild: "Borsa" },
  { normal: "Banco", wild: "Cattedra" },
  { normal: "Lavagna", wild: "LIM" },
  { normal: "Campanella", wild: "Sirena" },
  { normal: "Pagella", wild: "Voto" },
  { normal: "Bocciatura", wild: "Rimandato" },
  { normal: "Mensa", wild: "Panino" },

  // --- Casa (stanze & spazi) ---
  { normal: "Cucina", wild: "Bagno" },
  { normal: "Salotto", wild: "Camera da letto" },
  { normal: "Garage", wild: "Cantina" },
  { normal: "Terrazzo", wild: "Giardino" },
  { normal: "Scala", wild: "Ascensore" },
  { normal: "Portone", wild: "Cancello" },
  { normal: "Mansarda", wild: "Seminterrato" },
  { normal: "Corridoio", wild: "Ingresso" },

  // --- Animali domestici ---
  { normal: "Cane", wild: "Gatto" },
  { normal: "Criceto", wild: "Porcellino" },
  { normal: "Tartaruga", wild: "Sapo" },
  { normal: "Pesce", wild: "Squalo" },
  { normal: "Coniglio", wild: "Lepre" },
  { normal: "Pappagallo", wild: "Canarino" },
  { normal: "Furetto", wild: "Cincillà" },

  // --- Tempo libero & Hobby ---
  { normal: "Leggere", wild: "Scrivere" },
  { normal: "Disegnare", wild: "Colorare" },
  { normal: "Cucinare", wild: "Friggere" },
  { normal: "TV", wild: "Film" },
  { normal: "Passeggiata", wild: "Jogging" },
  { normal: "Carte", wild: "Dadi" },
  { normal: "Fotografia", wild: "Video" },
  { normal: "Cantare", wild: "Karaoke" },
  { normal: "Ballare", wild: "Yoga" },
  { normal: "Giardinaggio", wild: "Funghi" },
  { normal: "Pescare", wild: "Cacciare" },
  { normal: "Puzzle", wild: "Cruciverba" },
  { normal: "Figurine", wild: "Monete" },
  { normal: "Escursioni", wild: "Trekking" },

  // --- Supermercato (prodotti comuni) ---
  { normal: "Latte", wild: "Yogurt" },
  { normal: "Uova", wild: "Formaggio" },
  { normal: "Farina", wild: "Semola" },
  { normal: "Zucchero", wild: "Miele" },
  { normal: "Sale", wild: "Pepe" },
  { normal: "Olio", wild: "Burro" },
  { normal: "Pasta", wild: "Gnocchi" },
  { normal: "Riso", wild: "Orzo" },
  { normal: "Pane", wild: "Focaccia" },
  { normal: "Burro", wild: "Strutto" },
  { normal: "Panna", wild: "Crema" },
  { normal: "Brodo", wild: "Minestra" },
  { normal: "Pomodoro", wild: "Salsa" },
  { normal: "Piselli", wild: "Fagioli" },
  { normal: "Merendina", wild: "Crackers" },
  { normal: "Succo", wild: "Nettare" },
  { normal: "Acqua", wild: "Bibita" },
  { normal: "Caffè", wild: "Tè" },
  { normal: "Detersivo", wild: "Ammorbidente" },
  { normal: "Carta", wild: "Tovagliolo" },
  { normal: "Sacchetti", wild: "Buste" },

  // --- Meteo & Stagioni ---
  { normal: "Estate", wild: "Primavera" },
  { normal: "Autunno", wild: "Inverno" },
  { normal: "Sole", wild: "Nuvole" },
  { normal: "Ombrello", wild: "Impermeabile" },
  { normal: "Stivali", wild: "Scarpe" },
  { normal: "Giubbotto", wild: "Giacca" },
  { normal: "Sciarpa", wild: "Passamontagna" },
  { normal: "Crema", wild: "Lozione" },
  { normal: "Ventilatore", wild: "Condizionatore" },
  { normal: "Termosifone", wild: "Stufa" },
  { normal: "Coperta", wild: "Piumone" },

  // --- Mezzi di comunicazione ---
  { normal: "Telefonata", wild: "Videochiamata" },
  { normal: "SMS", wild: "Messaggio vocale" },
  { normal: "Email", wild: "Lettera cartacea" },
  { normal: "Giornale", wild: "Articolo" },
  { normal: "Radio", wild: "Podcast" },
  { normal: "Telegiornale", wild: "Notizie online" },
  { normal: "Manifesto", wild: "Volantino" },
  { normal: "Cartolina", wild: "Bigliettino" },

  // --- Ristorante & Bar (situazioni) ---
  { normal: "Ordinare", wild: "Prenotare" },
  { normal: "Menu", wild: "Piatto" },
  { normal: "Conto", wild: "Scontrino" },
  { normal: "Mancia", wild: "Coperto" },
  { normal: "Tavolo", wild: "Banco" },
  { normal: "Tovagliolo", wild: "Tovagliera" },
  { normal: "Acqua", wild: "Bibita" },
  { normal: "Aperitivo", wild: "Digestivo" },
  { normal: "Antipasto", wild: "Contorno" },
  { normal: "Dessert", wild: "Caffè" },

  // --- Ospedale & Salute ---
  { normal: "Visita", wild: "Consulto" },
  { normal: "Vaccino", wild: "Medicina" },
  { normal: "Sala", wild: "Pronto soccorso" },
  { normal: "Ricetta", wild: "Prescrizione" },
  { normal: "Cerotto", wild: "Benda" },
  { normal: "Sciroppo", wild: "Gocce" },
  { normal: "Pancia", wild: "Nausea" },
  { normal: "Gola", wild: "Raucedine" },
  { normal: "Raffreddore", wild: "Influenza" },
  { normal: "Febbre", wild: "Brividi" },
  { normal: "Ghiaccio", wild: "Pomata" },

  // --- Viaggio & Vacanza (situazioni) ---
  { normal: "Valigie", wild: "Bagaglio" },
  { normal: "Aereo", wild: "Treno" },
  { normal: "Check-in", wild: "Check-out" },
  { normal: "Camera", wild: "Suite" },
  { normal: "Colazione", wild: "Cena" },
  { normal: "Mappa", wild: "GPS" },
  { normal: "Valuta", wild: "Bancomat" },
  { normal: "Dogana", wild: "Visto" },
  { normal: "Turista", wild: "Viaggiatore" },
  { normal: "Foto", wild: "Video" },

  // --- Oggetti di uso quotidiano ---
  { normal: "Chiavi", wild: "Lucchetto" },
  { normal: "Portafoglio", wild: "Borsellino" },
  { normal: "Occhiali", wild: "Lenti" },
  { normal: "Cuffie", wild: "Auricolari" },
  { normal: "Caricabatterie", wild: "Powerbank" },
  { normal: "Agenda", wild: "Calendario" },
  { normal: "Penna", wild: "Matita" },
  { normal: "Accendino", wild: "Fiammiferi" },
  { normal: "Orologio", wild: "Cronometro" },
  { normal: "Ombrello", wild: "Mantello" },
  { normal: "Borsa", wild: "Valigia" },
  { normal: "Borsone", wild: "Zaino" },

  // --- Sport (situazioni & luoghi) ---
  { normal: "Campo", wild: "Pista" },
  { normal: "Spogliatoio", wild: "Palestra" },
  { normal: "Arbitro", wild: "Allenatore" },
  { normal: "Tifoso", wild: "Spettatore" },
  { normal: "Maglietta", wild: "Fascia" },
  { normal: "Pallone", wild: "Palla" },
  { normal: "Scarpe", wild: "Scarpini" },
  { normal: "Medaglia", wild: "Trofeo" },
  { normal: "Coppa", wild: "Campionato" },
  { normal: "Partita", wild: "Amichevole" },
  { normal: "Gol", wild: "Rigore" },
  { normal: "Fallo", wild: "Cartellino" },
  { normal: "Portiere", wild: "Attaccante" },
  { normal: "Difensore", wild: "Centrocampista" },

  // --- Feste (oggetti & attività) ---
  { normal: "Candeline", wild: "Fiaccole" },
  { normal: "Palloncini", wild: "Coriandoli" },
  { normal: "Carta", wild: "Sacchetto" },
  { normal: "Nastro", wild: "Fiocco" },
  { normal: "Buffet", wild: "Cena seduta" },
  { normal: "Discoteca", wild: "Festa in casa" },
  { normal: "DJ", wild: "Band" },
  { normal: "Invito", wild: "Convite" },
  { normal: "Foto", wild: "Video" },
  { normal: "Brindisi", wild: "Toast" },

  // --- Personaggi delle favole (nuovi) ---
  { normal: "Babbo", wild: "Befana" },
  { normal: "Fatina", wild: "Uomo" },
  { normal: "Lupo", wild: "Orco" },
  { normal: "Principe", wild: "Cavaliere" },
  { normal: "Matrigna", wild: "Strega" },
  { normal: "Mago", wild: "Stregone" },
  { normal: "Nano", wild: "Gnomo" },
  { normal: "Gigante", wild: "Mostro" },

  // --- Città italiane & luoghi famosi ---
  { normal: "Colosseo", wild: "Pantheon" },
  { normal: "Pisa", wild: "Belem" },
  { normal: "Milano", wild: "Firenze" },
  { normal: "Canale", wild: "Ponte" },
  { normal: "Vesuvio", wild: "Etna" },
  { normal: "Portofino", wild: "Cinque Terre" },
  { normal: "Como", wild: "Garda" },
  { normal: "Dolomiti", wild: "Appennini" },
  { normal: "Riviera", wild: "Costiera" },
  { normal: "Navona", wild: "Spagna" },

  // --- Vestiti (situazioni) ---
  { normal: "Eleganza", wild: "Casual" },
  { normal: "Cambio", wild: "Pigiama" },
  { normal: "Panni", wild: "Bucato" },
  { normal: "Stirare", wild: "Sgualcire" },
  { normal: "Scarpe", wild: "Stivali" },
  { normal: "Togliersi le scarpe in casa", wild: "Tenere le scarpe in casa" },

  // --- Mezzi di pagamento ---
  { normal: "Contanti", wild: "Bancomat" },
  { normal: "Scontrino", wild: "Ricevuta" },
  { normal: "Carta", wild: "Assegno" },
  { normal: "Portafoglio", wild: "Borsellino" },
  { normal: "Monete", wild: "Banconote" },

  // --- Natura (elementi semplici) ---
  { normal: "Pietra", wild: "Ciottolo" },
  { normal: "Ramo", wild: "Ramoscello" },
  { normal: "Foglia", wild: "Aghi di pino" },
  { normal: "Fiore", wild: "Rosa" },
  { normal: "Fungo", wild: "Porcino" },
  { normal: "Conchiglia", wild: "Corallo" },
  { normal: "Nido", wild: "Tana" },
  { normal: "Pozzanghera", wild: "Ruscello" },
  { normal: "Tramonto", wild: "Alba" },
  { normal: "Cielo", wild: "Atmosfera" },
  { normal: "Luna", wild: "Stella" },

  // --- Tecnologia & Social ---
  { normal: "Instagram", wild: "Facebook" },
  { normal: "WhatsApp", wild: "Telegram" },
  { normal: "Netflix", wild: "Disney" },
  { normal: "YouTube", wild: "TikTok" },
  { normal: "Spotify", wild: "Pandora" },
  { normal: "iPhone", wild: "Samsung" },
  { normal: "PlayStation", wild: "Xbox" },
  { normal: "Amazon", wild: "eBay" },
  { normal: "Google", wild: "Yahoo" },
  { normal: "Computer", wild: "Tablet" },

  // --- Intrattenimento ---
  { normal: "Cinema", wild: "Teatro" },
  { normal: "Film", wild: "Serie" },
  { normal: "Radio", wild: "Podcast" },
  { normal: "Libro", wild: "Fumetto" },
  { normal: "Musica", wild: "Canzone" },
  { normal: "Chitarra", wild: "Pianoforte" },
  { normal: "Batteria", wild: "Tromba" },
  { normal: "Violino", wild: "Flauto" },
  { normal: "Pittura", wild: "Scultura" },

  // --- Nuove parole singole comuni ---
  { normal: "Tavolo", wild: "Sedia" },
  { normal: "Tazza", wild: "Bicchiere" },
  { normal: "Piatto", wild: "Ciotola" },
  { normal: "Forchetta", wild: "Cucchiaio" },
  { normal: "Coltello", wild: "Forbici" },
  { normal: "Finestra", wild: "Porta" },
  { normal: "Muro", wild: "Soffitto" },
  { normal: "Pavimento", wild: "Tappeto" },
  { normal: "Quadro", wild: "Poster" },
  { normal: "Lampada", wild: "Lampadario" },
  { normal: "Specchio", wild: "Vetro" },
  { normal: "Cuscino", wild: "Lenzuolo" },
  { normal: "Coperta", wild: "Coltre" },
  { normal: "Vestito", wild: "Gonna" },
  { normal: "Camicia", wild: "Polo" },
  { normal: "Maglietta", wild: "Canottiera" },
  { normal: "Felpa", wild: "Maglione" },
  { normal: "Pantaloni", wild: "Bermuda" },
  { normal: "Costume", wild: "Slip" },
  { normal: "Giacca", wild: "Gilet" },
  { normal: "Mantello", wild: "Poncho" },
  { normal: "Cintura", wild: "Bretelle" },
  { normal: "Scarpa", wild: "Sandalo" },
  { normal: "Stivale", wild: "Stivaletto" },
  { normal: "Infradito", wild: "Zoccolo" },
  { normal: "Calzino", wild: "Calza" },
  { normal: "Calzettone", wild: "Mutanda" },
  { normal: "Reggiseno", wild: "Canottiera" },
  { normal: "Cappello", wild: "Berretto" },
  { normal: "Sciarpa", wild: "Foulard" },
  { normal: "Guanto", wild: "Moffola" },
  { normal: "Passamontagna", wild: "Balaclava" },
  { normal: "Anello", wild: "Braccialetto" },
  { normal: "Collana", wild: "Ciondolo" },
  { normal: "Orecchino", wild: "Monachella" },
  { normal: "Orologio", wild: "Sveglia" },
  { normal: "Portafoglio", wild: "Borsellino" },
  { normal: "Borsa", wild: "Borsetta" },
  { normal: "Zaino", wild: "Fagotto" },
  { normal: "Valigia", wild: "Trolley" },
  { normal: "Baule", wild: "Petto" },
  { normal: "Cassetto", wild: "Scaffale" },
  { normal: "Armadio", wild: "Guardaroba" },
  { normal: "Cassettiera", wild: "Comò" },
  { normal: "Tavolo", wild: "Scrivania" },
  { normal: "Sedia", wild: "Poltrona" },
  { normal: "Panca", wild: "Sgabello" },
  { normal: "Letto", wild: "Brandina" },
  { normal: "Lettino", wild: "Culla" },
  { normal: "Divano", wild: "Futon" },
  { normal: "Chaise", wild: "Dayletto" },
  { normal: "Frigorifero", wild: "Cantina" },
  { normal: "Congelatore", wild: "Cella" },
  { normal: "Forno", wild: "Tostapane" },
  { normal: "Microonde", wild: "Grill" },
  { normal: "Lavello", wild: "Rubinetto" },
  { normal: "Pentola", wild: "Padella" },
  { normal: "Padelletta", wild: "Casseruola" },
  { normal: "Mestolo", wild: "Cucchiaio di legno" },
  { normal: "Frusta", wild: "Spatola" },
  { normal: "Grattugia", wild: "Spremiagrumi" },
  { normal: "Tagliere", wild: "Colino" },
  { normal: "Coltello", wild: "Seghetto" },
  { normal: "Accetta", wild: "Mannaia" },
  { normal: "Martello", wild: "Mazza" },
  { normal: "Cacciavite", wild: "Chiave inglese" },
  { normal: "Pinza", wild: "Tenaglia" },
  { normal: "Trapano", wild: "Lima" },
  { normal: "Sega", wild: "Scalpello" },
  { normal: "Livella", wild: "Metro" },
  { normal: "Corda", wild: "Catena" },
  { normal: "Chiodo", wild: "Vite" },
  { normal: "Bullone", wild: "Dado" },
  { normal: "Gancio", wild: "Moschettone" },
  { normal: "Anello", wild: "Carabina" },
  { normal: "Lucchetto", wild: "Catenaccio" },
  { normal: "Maniglie", wild: "Pomello" },
  { normal: "Cerniera", wild: "Bottone" },
  { normal: "Zip", wild: "Velcro" },
  { normal: "Ago", wild: "Filo" },
  { normal: "Bottone", wild: "Automatico" },
  { normal: "Asola", wild: "Gancio" },
  { normal: "Orlo", wild: "Passante" },
  { normal: "Tasca", wild: "Piega" },
  { normal: "Risvolto", wild: "Polso" },
  { normal: "Colletto", wild: "Bavero" },
  { normal: "Spallina", wild: "Coulisse" },
  { normal: "Etichetta", wild: "Marca" },
  { normal: "Stemma", wild: "Logo" },
  { normal: "Ricamo", wild: "Stampa" },
  { normal: "Rete", wild: "Pizzo" },
  { normal: "Bottoni", wild: "Perle" },
  { normal: "Perline", wild: "Cristalli" },
  { normal: "Strass", wild: "Paillettes" },
  { normal: "Nastro", wild: "Passamaneria" },
  { normal: "Pizzo", wild: "Tulle" },
  { normal: "Velluto", wild: "Coraggio" },
  { normal: "Seta", wild: "Lino" },
  { normal: "Cotone", wild: "Lana" },
  { normal: "Poliestere", wild: "Acrilico" },
  { normal: "Nylon", wild: "Spandex" },
  { normal: "Pelle", wild: "Suede" },
  { normal: "Camoscio", wild: "Alcantara" },

  // --- Cibo & Bevande ---
  { normal: "Pizza", wild: "Focaccia" },
  { normal: "Hamburger", wild: "Hotdog" },
  { normal: "Pasta", wild: "Riso" },
  { normal: "Lasagna", wild: "Cannelloni" },
  { normal: "Gelato", wild: "Sorbetto" },
  { normal: "Carne", wild: "Pesce" },
  { normal: "Pollo", wild: "Tacchino" },
  { normal: "Sushi", wild: "Kebab" },
  { normal: "Pane", wild: "Grissino" },
  { normal: "Biscotto", wild: "Torta" },
  { normal: "Cioccolato", wild: "Caramella" },
  { normal: "Mela", wild: "Pera" },
  { normal: "Banana", wild: "Mango" },
  { normal: "Fragola", wild: "Ciliegia" },
  { normal: "Arancia", wild: "Limone" },
  { normal: "Caffè", wild: "Tè" },
  { normal: "Vino", wild: "Birra" },
  { normal: "Acqua", wild: "Succo" },
  { normal: "Latte", wild: "Yogurt" },
  { normal: "Coca", wild: "Pepsi" },

  // --- Casa ---
  { normal: "Letto", wild: "Divano" },
  { normal: "Tavolo", wild: "Sedia" },
  { normal: "Cucina", wild: "Bagno" },
  { normal: "Frigorifero", wild: "Forno" },
  { normal: "Lavatrice", wild: "Lavastoviglie" },
  { normal: "Doccia", wild: "Vasca" },
  { normal: "Armadio", wild: "Cassettiera" },
  { normal: "Porta", wild: "Finestra" },
  { normal: "Tetto", wild: "Pavimento" },
  { normal: "Giardino", wild: "Terrazzo" },

  // --- Abbigliamento ---
  { normal: "Maglietta", wild: "Camicia" },
  { normal: "Pantaloni", wild: "Jeans" },
  { normal: "Giacca", wild: "Cappotto" },
  { normal: "Scarpe", wild: "Stivali" },
  { normal: "Sandali", wild: "Infradito" },
  { normal: "Calzini", wild: "Mutande" },
  { normal: "Cappello", wild: "Sciarpa" },
  { normal: "Guanti", wild: "Cintura" },
  { normal: "Occhiali", wild: "Lenti" },
  { normal: "Orologio", wild: "Bracciale" },

  // --- Sport ---
  { normal: "Calcio", wild: "Rugby" },
  { normal: "Basket", wild: "Pallavolo" },
  { normal: "Tennis", wild: "Padel" },
  { normal: "Nuoto", wild: "Tuffi" },
  { normal: "Sci", wild: "Pattinaggio" },
  { normal: "Corsa", wild: "Salto" },
  { normal: "Boxe", wild: "Karate" },
  { normal: "Ciclismo", wild: "Moto" },
  { normal: "Palestra", wild: "Yoga" },

  // --- Natura & Animali ---
  { normal: "Cane", wild: "Gatto" },
  { normal: "Leone", wild: "Tigre" },
  { normal: "Elefante", wild: "Giraffa" },
  { normal: "Lupo", wild: "Volpe" },
  { normal: "Orso", wild: "Panda" },
  { normal: "Cavallo", wild: "Asino" },
  { normal: "Mucca", wild: "Maiale" },
  { normal: "Uccello", wild: "Farfalla" },
  { normal: "Pesce", wild: "Squalo" },
  { normal: "Mare", wild: "Montagna" },
  { normal: "Sole", wild: "Luna" },
  { normal: "Pioggia", wild: "Neve" },
  { normal: "Albero", wild: "Fiore" },
  { normal: "Prato", wild: "Deserto" },

  // --- Luoghi & Trasporti ---
  { normal: "Auto", wild: "Moto" },
  { normal: "Bici", wild: "Monopattino" },
  { normal: "Treno", wild: "Aereo" },
  { normal: "Nave", wild: "Barca" },
  { normal: "Bus", wild: "Taxi" },
  { normal: "Scuola", wild: "Lavoro" },
  { normal: "Ospedale", wild: "Farmacia" },
  { normal: "Banca", wild: "Posta" },
  { normal: "Stadio", wild: "Arena" },
  { normal: "Piazza", wild: "Via" },

  // --- Professioni ---
  { normal: "Dottore", wild: "Infermiere" },
  { normal: "Maestro", wild: "Preside" },
  { normal: "Poliziotto", wild: "Pompiere" },
  { normal: "Cuoco", wild: "Cameriere" },
  { normal: "Pilota", wild: "Autista" },
  { normal: "Attore", wild: "Cantante" },
  { normal: "Avvocato", wild: "Giudice" }

];
